version: '3.8'

volumes:
  redisdata:

networks:
  default:
    driver: bridge

services:
  bff:
    build:
      context: .
    container_name: bff
    env_file:
      - .env.dev
    command: "npm run start:dev"
    ports:
      - "3000:3000"
    volumes:
      - "./:/project"
    networks:
      - default

  redis:
    image: "redis:7.4.1"
    container_name: bff-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - default
